# default:
#   host: localhost
#   port: 6379
# development:
#   db: 0
# #  namespace: appname_dev
# test:
#   db: 1
# #  namespace: appname_test
# production:
#   db: 2
#   host: localhost
# #  namespace: appname_prod


default:
  host: 10.61.5.44
  port: 6399
development:
  db: 0
  host: localhost
  port: 6379
#  namespace: appname_dev
test:
  db: 1
  host: localhost
  port: 6379
#  namespace: appname_test
production:
  db: 2
  host: 10.61.5.44
  port: 6399
#  namespace: appname_prod